=== panedrone/sqldalmaker/src/resources/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="folders" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="dto" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="dao" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="external-vm-file" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="ide" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cpp" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="jdbc" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="type-map" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="global-macros" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="sdm-scripts" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="folders">
        <xs:complexType>
            <xs:attribute name="target" use="required" type="xs:string"/>
            <xs:attribute name="sql" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dto">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="inheritance" use="required" type="xs:string"/>
            <xs:attribute name="field-names-mode" use="required" type="xs:int"/>
            <xs:attribute name="single-file" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dao">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="external-vm-file">
        <xs:complexType>
            <xs:attribute name="path" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ide">
        <xs:complexType>
            <xs:attribute name="event-log" use="required" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cpp">
        <xs:complexType>
            <xs:attribute name="class-prefix" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="jdbc">
        <xs:complexType>
            <xs:attribute name="jar" use="required" type="xs:string"/>
            <xs:attribute name="class" use="required" type="xs:string"/>
            <xs:attribute name="url" use="required" type="xs:string"/>
            <xs:attribute name="user" use="required" type="xs:string"/>
            <xs:attribute name="pwd" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="type-map">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="type"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="default" use="required"
                          type="xs:string"/>
        </xs:complexType>
        <xs:unique name="type-detected">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@detected"/>
        </xs:unique>
    </xs:element>
    <xs:element name="type">
        <xs:complexType>
            <xs:attribute name="detected" use="required" type="xs:string"/>
            <xs:attribute name="target" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="global-macros">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="global-macro"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="global-macro-id">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="global-macro">
        <xs:complexType>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="value" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="var" type="xs:string"/>
    <xs:attribute name="in" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="params" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>

    <xs:element name="sdm-scripts">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="sdm-script"/>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="sdm-script-name">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="sdm-script">
        <xs:complexType>
            <xs:choice minOccurs="1">
                <xs:element name="vm" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="vm-xml" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="vm-xml">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="if">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="elseif" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element ref="else" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="elseif">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="else">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="foreach">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                    <xs:attribute ref="in" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="macro">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="name" use="required"/>
                    <xs:attribute ref="params" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="set">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="print">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="br">
        <xs:complexType>
            <xs:attribute name="br" default="" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="root-statements">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:choice>
                <xs:element ref="if"/>
                <xs:element ref="set"/>
                <xs:element ref="foreach"/>
                <xs:element ref="macro"/>
                <xs:element ref="print"/>
                <xs:element ref="br"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== panedrone/sqldalmaker/src/resources/data_store_django.py.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root) -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="dbal" sql="sdm/sql"/>

    <dto scope="" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="mysql-connector-java-8.0.13.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/todolist" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.3.4.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/todolist" user="postgres" pwd="sa" />-->

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <type-map default="">

        <!-- ***** django (dj) ****************** -->

        <type detected="dj-java.lang.Short" target="${dj-type}|0:IntegerField"/>
        <type detected="dj-java.lang.Integer" target="${dj-type}|0:IntegerField"/>
        <type detected="dj-java.lang.Long" target="${dj-type}|0:BigIntegerField"/>

        <type detected="dj-java.lang.Float" target="${dj-type}|0:FloatField"/>
        <type detected="dj-java.lang.Double" target="${dj-type}|0:FloatField"/>

        <type detected="dj-java.math.BigDecimal"
              target="${dj-type}|0:DecimalField|1:, max_digits=12, decimal_places=2"/>
        <type detected="dj-java.math.BigDecimal+auto" target="${dj-type}|0:BigAutoField"/>

        <type detected="dj-java.util.Date" target="${dj-type}|0:DateTimeField"/>
        <type detected="dj-java.lang.String" target="${dj-type}|0:CharField"/>
        <type detected="dj-java.lang.Boolean" target="${dj-type}|0:BooleanField"/>
        <type detected="dj-byte[]" target="${dj-type}|0:BinaryField"/>

        <type detected="dj-java.lang.Object" target="${dj-type}|0:TextField"/>

        <type detected="dj-java.lang.Integer+autoincrement" target="${dj-type}|0:AutoField"/>
        <type detected="dj-java.lang.Integer+auto" target="${dj-type}|0:AutoField"/>

        <type detected="dj-int" target="${dj-type}|0:IntegerField"/>
        <type detected="dj-long" target="${dj-type}|0:BigIntegerField"/>

        <type detected="dj-float" target="${dj-type}|0:FloatField"/>

        <type detected="dj-date" target="${dj-type}|0:DateTimeField"/>
        <type detected="dj-str" target="${dj-type}|0:CharField"/>
        <type detected="dj-bool" target="${dj-type}|0:BooleanField"/>
        <!--        <type detected="dj-byte[]" target="${dj-type}|0:BinaryField"/> -->

        <type detected="dj-object" target="${dj-type}|0:CharField|1:, max_length=256"/>

        <!-- ****** raw SQL, params, ret-values ************************ -->

        <type detected="java.lang.Short" target="int"/>
        <type detected="java.lang.Integer" target="int"/>
        <type detected="java.lang.Long" target="long"/>

        <type detected="java.lang.Double" target="float"/>
        <type detected="java.lang.Float" target="float"/>
        <type detected="java.math.BigDecimal" target="float"/>

        <type detected="java.util.Date" target="str"/>
        <type detected="java.lang.String" target="str"/>
        <type detected="java.lang.Boolean" target="bool"/>
        <type detected="byte[]" target="bytes"/>

        <type detected="java.lang.Object" target="object"/>

    </type-map>

    <macros>

        <!-- =built-in= is a key-word -->

        <macro name="${column}" value="=built-in="/>
        <macro name="${lower_snake_case(column)}" value="=built-in="/>
        <macro name="${camelCase(column)}" value="=built-in="/>
        <macro name="${TitleCase(column)}" value="=built-in="/>
        <macro name="${kebab-case(column)}" value="=built-in="/>

        <!-- djando field: -->

        <macro name="${dj-type}" value="${dj-field}"/>

        <!-- In VM-based macros intended to render the fields/columns,
             "$fi" is a predefined variable of class FieldInfo:

                class FieldInfo:
                    String getName()
                    String getType()
                    String getScalarType()
                    String getColumnName()
                    int getColumnSize()
                    boolean isAI()
                    boolean isPK()
                    String getFK()
                    boolean isNullable()
                    boolean isIndexed()
                    boolean isUnique()
                    String getComment()
                    String getterMethod()
                    String setterMethod()
           -->

        <macro name="${dj-field}">
            <vm>
                <![CDATA[
= models.#if($fi.AI)AutoField#else${0}#end(db_column='$fi.ColumnName'#if($fi.ColumnSize>0), max_length=$fi.ColumnSize#end
#if($fi.PK), primary_key=True#else
#if($fi.Indexed), db_index=True#end
#if($fi.Unique), unique=True#end
#if($fi.Nullable), blank=True, null=True#end
#end${1})${comment}]]>
            </vm>
        </macro>

        <macro name="${dj-field-vm-xml}">
            <vm-xml>
                <print var="= models."/>
                <if var="$fi.AI">
                    <print var="AutoField"/>
                    <else>
                        <print var="${0}"/>
                    </else>
                </if>
                <print var="(db_column='$fi.ColumnName'"/>
                <if var="$fi.isPK()">
                    <print var=", primary_key=True"/>
                </if>
                <if var="$fi.ColumnSize>0">
                    <print var=", max_length=$fi.ColumnSize"/>
                </if>
                <if var="!$fi.PK">
                    <if var="$fi.Indexed">
                        <print var=", db_index=True"/>
                    </if>
                    <if var="$fi.Unique">
                        <print var=", unique=True"/>
                    </if>
                    <if var="$fi.Nullable">
                        <print var=", blank=True, null=True"/>
                    </if>
                </if>
                <print var="${1})${comment}"/>
            </vm-xml>
        </macro>

    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/data_store_no_orm_cx_oracle.py.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root) -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="dbal" sql="sdm/sql"/>

    <dto scope="" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"
          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>

    <type-map default="">

        <type detected="java.lang.Short" target="int"/>
        <type detected="java.lang.Integer" target="int"/>
        <type detected="java.lang.Long" target="long"/>

        <type detected="java.lang.Double" target="float"/>
        <type detected="java.lang.Float" target="float"/>
        <type detected="java.math.BigDecimal" target="float"/>

        <type detected="java.util.Date" target="str"/>
        <type detected="java.lang.String" target="str"/>
        <type detected="java.lang.Boolean" target="bool"/>
        <type detected="byte[]" target="bytes"/>

        <type detected="java.lang.Object" target="object"/>

    </type-map>

    <macros>
    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore.java.android.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root). -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="app/src/main/java" sql="sdm/sql"/>

    <!-- field-names-mode: 0 - TitleCase, 1 - camelCase; 2 - snake_case -->

    <!-- scope: the name of DTO package -->

    <dto scope="sdm.android.thesaurus.dto" inheritance="" field-names-mode="1" macro=""/>

    <!-- scope: the name of DAO package -->

    <dao scope="sdm.android.thesaurus.dao" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <cpp class-prefix=""/>

    <jdbc jar="sdm/sqlite-jdbc-3.41.2.1.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/app/src/main/java/sqldalmaker/thesaurus.sqlite" user="" pwd=""/>

    <type-map default="">
        <!-- On Dev. PC, it is Integer, but in Android run-time it is Long -->
        <type detected="java.lang.Integer" target="Long -> getLong"/>
        <type detected="java.lang.Double" target="Double -> getDouble"/>
        <type detected="java.lang.String" target="String -> getString"/>
        <type detected="byte[]" target="byte[] -> getBytes"/>
    </type-map>

    <macros>
    </macros>

</settings>
