=== panedrone/sqldalmaker/src/resources/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="folders" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="dto" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="dao" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="external-vm-file" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="ide" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cpp" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="jdbc" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="type-map" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="global-macros" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="sdm-scripts" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="folders">
        <xs:complexType>
            <xs:attribute name="target" use="required" type="xs:string"/>
            <xs:attribute name="sql" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dto">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="inheritance" use="required" type="xs:string"/>
            <xs:attribute name="field-names-mode" use="required" type="xs:int"/>
            <xs:attribute name="single-file" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dao">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="external-vm-file">
        <xs:complexType>
            <xs:attribute name="path" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ide">
        <xs:complexType>
            <xs:attribute name="event-log" use="required" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cpp">
        <xs:complexType>
            <xs:attribute name="class-prefix" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="jdbc">
        <xs:complexType>
            <xs:attribute name="jar" use="required" type="xs:string"/>
            <xs:attribute name="class" use="required" type="xs:string"/>
            <xs:attribute name="url" use="required" type="xs:string"/>
            <xs:attribute name="user" use="required" type="xs:string"/>
            <xs:attribute name="pwd" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="type-map">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="type"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="default" use="required"
                          type="xs:string"/>
        </xs:complexType>
        <xs:unique name="type-detected">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@detected"/>
        </xs:unique>
    </xs:element>
    <xs:element name="type">
        <xs:complexType>
            <xs:attribute name="detected" use="required" type="xs:string"/>
            <xs:attribute name="target" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="global-macros">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="global-macro"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="global-macro-id">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="global-macro">
        <xs:complexType>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="value" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="var" type="xs:string"/>
    <xs:attribute name="in" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="params" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>

    <xs:element name="sdm-scripts">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="sdm-script"/>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="sdm-script-name">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="sdm-script">
        <xs:complexType>
            <xs:choice minOccurs="1">
                <xs:element name="vm" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="vm-xml" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="vm-xml">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="if">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="elseif" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element ref="else" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="elseif">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="else">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="foreach">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                    <xs:attribute ref="in" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="macro">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="name" use="required"/>
                    <xs:attribute ref="params" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="set">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="print">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="br">
        <xs:complexType>
            <xs:attribute name="br" default="" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="root-statements">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:choice>
                <xs:element ref="if"/>
                <xs:element ref="set"/>
                <xs:element ref="foreach"/>
                <xs:element ref="macro"/>
                <xs:element ref="print"/>
                <xs:element ref="br"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== panedrone/sqldalmaker/src/resources/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="settings.xsd">

	<!-- target: base path to the folder/package of generated files (relative 
		to the project root); ensure presence of __init__.py for Python; -->
	<!-- sql: base folder of SQL files (relative to the project root); -->

	<folders target="src" sql="sqldalmaker/sql" />

	<!-- scope: (only Java and PHP) package name of DTO classes for Java or 
		name-space name of DTO classes for PHP; -->
	<!-- inheritance: (only Java) fully-qualified name of base class; example 
		for GWT: 1) inheritance="implements com.google.gwt.user.client.rpc.IsSerializable" 
		2) target class: public class Word implements com.google.gwt.user.client.rpc.IsSerializable... -->
	<!-- field-names-mode (Java only): 0 - as column names; 1 - camelCase; 2 - snake_case; -->

	<dto scope="com.mycom.myproject.dto" inheritance=""
		field-names-mode="0" />

	<!-- scope: (only Java and PHP) package name of DAO classes for Java or 
		namespace name of DAO classes for PHP; -->

	<dao scope="com.mycom.myproject.dao" />

	<!-- location of external VM file (relative to the project root): -->

	<external-vm-file path="" />

	<!-- IDE integration -->

	<ide event-log="true" />

	<!-- prefix of generated C++ classes: -->

	<cpp class-prefix="" />

	<!-- jar: location of JDBC driver JAR file (relative to the project root); -->
	<!-- class: JDBC driver class name; -->
	<!-- url: JDBC connection URL (use $PROJECT_DIR$ or ${project_loc} if you 
		need to specify project path); -->
	<!-- user: user name; -->
	<!-- pwd: password; -->

	<jdbc jar="lib/mysql-connector-java-5.1.22-bin.jar"
		class="com.mysql.jdbc.Driver" url="jdbc:mysql://localhost/orders"
		user="root" pwd="root" />

	<!-- At the moment, type-map is used only for C++. Below is an example for 
		C++ and SQLite. -->

	<type-map default="CValue">
		<type java="java.lang.Long" target="CLong" />
		<type java="java.lang.Double" target="CDouble" />
		<type java="java.lang.String" target="CText" />
		<type java="byte[]" target="CBlob" />
	</type-map>

</settings>

=== panedrone/sqldalmaker/src/resources/data_store_no_orm.go.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!--    (*) below means "a path relative to the project root"   -->

    <!-- target: the same as "module" in "go.mod" -->

    <!-- sql: base folder of SQL files (*) -->

    <folders target="sdm_demo_todolist" sql="sqlx/sdm/sql"/>

    <!-- scope: base folder of generated DTO files (*) -->

    <!-- field-names-mode: 0 - TitleCase -->

    <!-- macro: VM template to render DAO classes

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dto ... macro="<path>/<name>.vm"/> -->

    <dto scope="no_orm/dbal/dto" inheritance="" field-names-mode="0" macro=""/>

    <!-- scope: base folder of generated DAO files (*) -->

    <!-- field-assign-mode (Go only)":

            0 - by column name
            1 - by field position
            2 - ptr to DTO or ptr to slice of DTO-s (Gorm, sqlx)
            3 - ptr to resulting slice of DTO-s (Gorm, sqlx) -->

    <!-- macro: VM template to render DAO classes

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dao ... macro="<path>/<name>.vm"/> -->

    <dao scope="no_orm/dbal" field-assign-mode="3" macro=""/>

    <ide event-log="true"/>

    <!--    <jdbc jar="lib/sqlite-jdbc-3.45.1.0.jar" class="org.sqlite.JDBC"-->
    <!--          url="jdbc:sqlite:$PROJECT_DIR$/db/todolist.sqlite" user="" pwd=""/>-->

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <!--    <jdbc jar="mysql-connector-j-8.4.0.jar"-->
    <!--          class="com.mysql.cj.jdbc.Driver" url="jdbc:mysql://localhost/orders" user="root" pwd="sa"/>-->

    <jdbc jar="postgresql-42.7.3.jar" class="org.postgresql.Driver"
          url="jdbc:postgresql://localhost/orders" user="postgres" pwd="sa"/>

    <type-map default="">

        <!-- sqlite3 -->

        <!--        <type detected="java.lang.Integer" target="int64${json} -> SetInt64"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->
        <!--        <type detected="byte[]" target="[]byte${json} -> SetBytes"/>-->
        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

        <!-- mysql, postgres, sql server -->

        <type detected="java.util.UUID" target="github.com/google/uuid:uuid.UUID${json} -> Scan"/>
        <type detected="java.sql.Array" target="[]string${json}"/>

        <type detected="java.lang.Short" target="int16${json} -> SetInt16"/>
        <type detected="java.lang.Integer" target="int32${json} -> SetInt32"/>
        <type detected="java.lang.Long" target="int64${json} -> SetInt64"/>

        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>
        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>
        <type detected="java.math.BigDecimal" target="float64${json} -> SetFloat64"/>

        <type detected="java.lang.String" target="string${json} -> SetString"/>
        <type detected="byte[]" target="[]byte${json} -> "/>
        <type detected="java.lang.Boolean" target="bool${json} -> SetBool"/>

        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>
        <type detected="java.time.LocalDateTime" target="time:time.Time${json} -> SetTime"/>

        <type detected="java.lang.Object" target="interface{}${json}"/>

        <!-- oracle -->

        <!--        <type detected="java.math.BigDecimal" target="${json-ora-num}"/>-->
        <!--        <type detected="java.math.BigDecimal+auto" target="${json-ora-num}"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->

        <!--        <type detected="java.util.Date" target="${json-time}"/>-->
        <!--        <type detected="java.time.ZonedDateTime" target="${json-time}"/>-->
        <!--        <type detected="java.time.LocalDateTime" target="${json-time}"/>-->

        <!--        <type detected="byte[]" target="string${json} -> SetBytes"/>-->
        <!--        <type detected="java.lang.Boolean" target="int64${json} -> SetBool"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}{$json}"/>-->

    </type-map>

    <macros>

        <macro value="=built-in=" name="${column}"/>
        <macro value="=built-in=" name="${lower_snake_case(column)}"/>
        <macro value="=built-in=" name="${camelCase(column)}"/>
        <macro value="=built-in=" name="${TitleCase(column)}"/>
        <macro value="=built-in=" name="${kebab-case(column)}"/>

        <macro name="${json-col}" value="${lower_snake_case(column)}"/>

        <macro name="${json}" value=" `json:&quot;${json-col}${0}&quot;`"/>

        <macro name="${json-time}" value="time:time.Time${json} -> SetTime"/>

        <macro name="${json-ora-num}" value="${ora-num} `json:&quot;${json-col}${0}&quot;` -> SetNum"/>

        <macro name="${ora-num}">
            <vm-xml>
                <if var="$fi.Precision == 38 &amp;&amp; $fi.Scale == 0">
                    <print var=" int64"/>
                    <else>
                        <print var=" github.com/godror/godror:godror.Number"/>
                    </else>
                </if>
            </vm-xml>
        </macro>

    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore_Doctrine_ORM.php.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root). -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="api" sql="sdm/sql"/>

    <!-- scope: the name of DTO namespace. An empty one is OK. -->

    <!-- field-names-mode: 0 - TitleCase, 1 - camelCase; 2 - snake_case -->

    <dto scope="svc/models" inheritance="" field-names-mode="2" macro=""/>

    <!-- scope: the name of DTO namespace. An empty one is OK. -->

    <dao scope="svc/dao" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <cpp class-prefix=""/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="mysql-connector-java-8.0.13.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/todolist" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.3.4.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/todolist" user="postgres" pwd="sa" />-->

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <type-map default="">

        <!-- ******   PHP Doctrine   ****** -->

        <!-- https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html-->

        <type detected="doctrine-java.lang.Short" target="${doctrine-type}|0:smallint|1:int"/>
        <type detected="doctrine-java.lang.Integer" target="${doctrine-type}|0:integer|1:int"/>
        <type detected="doctrine-java.lang.Long" target="${doctrine-type}|0:bigint|1:string"/>

        <type detected="doctrine-java.lang.Float" target="${doctrine-type}|0:float|1:float"/>
        <type detected="doctrine-java.lang.Double" target="${doctrine-type}|0:float|1:float"/>
        <type detected="doctrine-java.math.BigDecimal" target="${doctrine-type}|0:decimal|1:string"/>

        <type detected="doctrine-java.util.Date" target="${doctrine-type}|0:datetime|1:\DateTime"/>
        <type detected="doctrine-java.lang.String" target="${doctrine-type}|0:string|1:string"/>
        <type detected="doctrine-java.lang.Boolean" target="${doctrine-type}|0:boolean|1:bool"/>
        <type detected="doctrine-byte[]" target="${doctrine-type}|0:array|1:array"/>
        <type detected="doctrine-java.lang.Object" target="${doctrine-type}|0:object|1:object"/>

        <!-- ******   PHP scalar types  ****** -->

        <type detected="java.lang.Short" target="int"/>
        <type detected="java.lang.Integer" target="int"/>
        <type detected="java.lang.Long" target="int"/>

        <type detected="java.lang.Float" target="float"/>
        <type detected="java.lang.Double" target="float"/>
        <type detected="java.math.BigDecimal" target="float"/>

        <type detected="java.util.Date" target="string"/>
        <type detected="java.lang.String" target="string"/>
        <type detected="java.lang.Boolean" target="bool"/>
        <type detected="byte[]" target="array"/>
        <type detected="java.lang.Object" target="object"/>

    </type-map>

    <macros>

        <!-- =built-in= is a key-word -->

        <macro name="${column}" value="=built-in="/>
        <macro name="${lower_snake_case(column)}" value="=built-in="/>
        <macro name="${camelCase(column)}" value="=built-in="/>
        <macro name="${TitleCase(column)}" value="=built-in="/>
        <macro name="${kebab-case(column)}" value="=built-in="/>

        <!-- PHP Doctrine ORM field type: -->

        <!-- https://www.doctrine-project.org/projects/doctrine-orm/en/2.11/reference/attributes-reference.html#attrref_column-->

        <macro name="${doctrine-type}">
            <vm-xml>
                <print var="@ORM\Column(name=&quot;${column}&quot;, type=&quot;${0}&quot;"/>
                <if var="$fi.ColumnSize>0">
                    <print var=", length=$fi.ColumnSize"/>
                </if>
                <if var="!$fi.PK">
                    <if var="$fi.Unique">
                        <print var=", unique=true"/>
                    </if>
                    <if var="$fi.Nullable">
                        <print var=", nullable=true"/>
                    </if>
                </if>
                <print var=")"/>
                <if var="$fi.PK">
                    <br/>
                    <br/>
                    <print var="     * @ORM\Id"/>
                </if>
                <if var="$fi.AI">
                    <br/>
                    <br/>
                    <print var="     * @ORM\GeneratedValue"/>
                </if>
                <br/>
                <br/>
                <print var="     * @var ${1}"/>
            </vm-xml>
        </macro>

    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore.java.JDBC.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root). -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="src" sql="sdm/sql"/>

    <!-- field-names-mode: 0 - TitleCase, 1 - camelCase; 2 - snake_case -->

    <!-- scope: the name of DTO package -->

    <dto scope="com.sdm.thesaurus.dto" inheritance="" field-names-mode="1" macro=""/>

    <!-- scope: the name of DAO package -->

    <dao scope="com.sdm.thesaurus.dao" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <cpp class-prefix=""/>

    <jdbc jar="sdm/sqlite-jdbc-3.41.2.1.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/thesaurus.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="lib/mysql-connector-java-8.0.13.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/sakila" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.2.9.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/orders" user="postgres" pwd="sa" />-->

    <!--    <jdbc jar="lib/ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521:XE" user="orders" pwd="sa"/>-->

    <!--    <jdbc jar="mssql-jdbc-8.2.2.jre8.jar" class="com.microsoft.sqlserver.jdbc.SQLServerDriver"-->
    <!--          url="jdbc:sqlserver://localhost:1433;instance=SQLEXPRESS;databaseName=AdventureWorks2014" user="sa" pwd="root"/>-->

    <type-map default="">

        <type detected="java.lang.Short" target="Short -> getShort"/>
        <type detected="java.lang.Integer" target="Integer -> getInteger"/>
        <type detected="java.lang.Long" target="Long -> getLong"/>

        <type detected="java.lang.Float" target="Float -> getFloat"/>
        <type detected="java.lang.Double" target="Double -> getDouble"/>
        <type detected="java.math.BigDecimal" target="java.math.BigDecimal -> getBigDecimal"/>

        <type detected="java.lang.String" target="String -> getString"/>
        <type detected="java.util.Date" target="java.util.Date -> getDate"/>
        <type detected="byte[]" target="byte[] -> getBytes"/>
        <type detected="java.lang.Boolean" target="Boolean -> getBoolean"/>

    </type-map>

    <macros>
    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore.cpp.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <folders target="" sql="sqldalmaker/sql" />

    <dto scope="" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <type-map default="CValue">
        <type detected="java.lang.Integer" target="CLong" />
        <type detected="java.lang.Long" target="CLong" />
        <type detected="java.lang.Double" target="CDouble" />
        <type detected="java.lang.String" target="CText" />
        <type detected="byte[]" target="CBlob" />
    </type-map>

    <macros>
    </macros>

</settings>
