=== panedrone/sqldalmaker/src/resources/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="folders" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="dto" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="dao" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="external-vm-file" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="ide" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cpp" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="jdbc" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="type-map" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="global-macros" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="sdm-scripts" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="folders">
        <xs:complexType>
            <xs:attribute name="target" use="required" type="xs:string"/>
            <xs:attribute name="sql" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dto">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
            <xs:attribute name="inheritance" use="required" type="xs:string"/>
            <xs:attribute name="field-names-mode" use="required" type="xs:int"/>
            <xs:attribute name="single-file" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="dao">
        <xs:complexType>
            <xs:attribute name="scope" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="external-vm-file">
        <xs:complexType>
            <xs:attribute name="path" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="ide">
        <xs:complexType>
            <xs:attribute name="event-log" use="required" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="cpp">
        <xs:complexType>
            <xs:attribute name="class-prefix" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="jdbc">
        <xs:complexType>
            <xs:attribute name="jar" use="required" type="xs:string"/>
            <xs:attribute name="class" use="required" type="xs:string"/>
            <xs:attribute name="url" use="required" type="xs:string"/>
            <xs:attribute name="user" use="required" type="xs:string"/>
            <xs:attribute name="pwd" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="type-map">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="type"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="default" use="required"
                          type="xs:string"/>
        </xs:complexType>
        <xs:unique name="type-detected">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@detected"/>
        </xs:unique>
    </xs:element>
    <xs:element name="type">
        <xs:complexType>
            <xs:attribute name="detected" use="required" type="xs:string"/>
            <xs:attribute name="target" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="global-macros">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="global-macro"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="global-macro-id">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="global-macro">
        <xs:complexType>
            <xs:attribute name="name" use="required" type="xs:string"/>
            <xs:attribute name="value" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="var" type="xs:string"/>
    <xs:attribute name="in" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="params" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>

    <xs:element name="sdm-scripts">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="sdm-script"/>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="sdm-script-name">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="sdm-script">
        <xs:complexType>
            <xs:choice minOccurs="1">
                <xs:element name="vm" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="vm-xml" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="vm-xml">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="if">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="elseif" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:element ref="else" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="elseif">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="else">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements"/>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="foreach">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="var" use="required"/>
                    <xs:attribute ref="in" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="macro">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="root-statements">
                    <xs:attribute ref="name" use="required"/>
                    <xs:attribute ref="params" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="set">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="print">
        <xs:complexType>
            <xs:attribute ref="var" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="br">
        <xs:complexType>
            <xs:attribute name="br" default="" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="root-statements">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:choice>
                <xs:element ref="if"/>
                <xs:element ref="set"/>
                <xs:element ref="foreach"/>
                <xs:element ref="macro"/>
                <xs:element ref="print"/>
                <xs:element ref="br"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== panedrone/sqldalmaker/src/resources/data_store_sqlalchemy.py.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root) -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="dbal" sql="sdm/sql"/>

    <dto scope="" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="mysql-connector-java-8.0.13.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/todolist" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.3.4.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/todolist" user="postgres" pwd="sa" />-->

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <type-map default="">

        <!-- ***** sqlalchemy (sa) ****************** -->

        <!-- all numerics for oracle_cx -->

<!--        <type detected="sa-java.math.BigDecimal" target="${sa-type}|0:NUMBER"/>-->
<!--        <type detected="sa-java.math.BigDecimal+auto"-->
<!--              target="${sa-type}|0:NUMBER|1:, autoincrement=True|comment:  # IDENTITY"/>-->

        <!-- numerics for others -->

        <type detected="sa-java.lang.Short" target="${sa-type}|0:SmallInteger"/>
        <type detected="sa-java.lang.Integer" target="${sa-type}|0:Integer"/>
        <type detected="sa-java.lang.Long" target="${sa-type}|0:BigInteger"/>

        <type detected="sa-java.lang.Float" target="${sa-type}|0:Float"/>
        <type detected="sa-java.lang.Double" target="${sa-type}|0:Float"/>
        <type detected="sa-java.math.BigDecimal" target="${sa-type}|0:Float"/>

        <type detected="sa-java.util.Date" target="${sa-type}|0:DateTime"/>
        <type detected="sa-java.time.ZonedDateTime" target="${sa-type}|0:DateTime"/>
        <type detected="sa-ava.time.LocalDateTime" target="${sa-type}|0:DateTime"/>

        <type detected="sa-java.lang.String" target="${sa-type}|0:String"/>
        <type detected="sa-java.lang.Boolean" target="${sa-type}|0:Boolean"/>
        <type detected="sa-byte[]" target="${sa-type}|0:LargeBinary"/>

        <type detected="sa-java.lang.Object" target="${sa-type-unknown}"/>

        <!-- ****** raw SQL, params, ret-values ************************ -->

        <type detected="java.lang.Short" target="int"/>
        <type detected="java.lang.Integer" target="int"/>
        <type detected="java.lang.Long" target="long"/>

        <type detected="java.lang.Double" target="float"/>
        <type detected="java.lang.Float" target="float"/>
        <type detected="java.math.BigDecimal" target="float"/>

        <type detected="java.util.Date" target="datetime.datetime"/>
        <type detected="java.time.ZonedDateTime" target="datetime.datetime"/>
        <type detected="java.time.LocalDateTime" target="datetime.datetime"/>

        <type detected="java.lang.String" target="str"/>
        <type detected="java.lang.Boolean" target="bool"/>
        <type detected="byte[]" target="bytes"/>

        <type detected="java.lang.Object" target="object"/>

    </type-map>

    <macros>

        <!-- =built-in= is a key-word -->

        <macro name="${column}" value="=built-in="/>
        <macro name="${lower_snake_case(column)}" value="=built-in="/>
        <macro name="${camelCase(column)}" value="=built-in="/>
        <macro name="${TitleCase(column)}" value="=built-in="/>
        <macro name="${kebab-case(column)}" value="=built-in="/>

        <!-- go json tags: -->

        <macro name="${col}" value="${lower_snake_case(column)}"/>

        <macro name="${json}" value=" `json:&quot;${col}${0}&quot;`"/>

        <!-- sqlalchemy Column: -->

        <macro name="${sa-type-unknown}" value="${sa-column-base}|type:"/>
        <macro name="${sa-type}" value="${sa-column-base}|type:, ${0}"/>

        <!-- In VM-based macros intended to render the fields/columns,
             "$fi" is a predefined variable of class FieldInfo:

                class FieldInfo:
                    String getName()
                    String getType()
                    String getColumnName()
                    int getColumnSize()
                    boolean isAI()
                    boolean isPK()
                    String getFK()
                    boolean isNullable()
                    boolean isIndexed()
                    boolean isUnique()
                    String getComment()
                    String getterMethod()
                    String setterMethod()
                        -->

        <macro name="${sa-column-base}">
            <vm>
                <![CDATA[= Column('${column}'${type}#if($fi.ColumnSize>0)($fi.ColumnSize)#end#if($fi.FK), ForeignKey('$fi.FK')#end
#if($fi.PK), primary_key=True#end
#if($fi.AI), autoincrement=True#end
#if(!$fi.PK)
#if($fi.Indexed), index=True#end
#if($fi.Unique), unique=True#end
#if($fi.Nullable), nullable=True#end
#end)${comment}]]>
            </vm>
        </macro>


        <macro name="${sa-column-base-vm-xml}">
            <vm-xml>
                <print var="= Column('${column}'${type}"/>
                <if var="$fi.ColumnSize>0">
                    <print var="($fi.ColumnSize)"/>
                </if>
                <if var="$fi.FK">
                    <print var=", ForeignKey('$fi.FK')"/>
                </if>
                <if var="$fi.PK">
                    <print var=", primary_key=True"/>
                </if>
                <if var="$fi.AI">
                    <print var=", autoincrement=True"/>
                </if>
                <if var="!$fi.PK">
                    <if var="$fi.Indexed">
                        <print var=", index=True"/>
                    </if>
                    <if var="$fi.Unique">
                        <print var=", unique=True"/>
                    </if>
                    <if var="$fi.Nullable">
                        <print var=", nullable=True"/>
                    </if>
                </if>
                <print var=")${comment}"/>
            </vm-xml>
        </macro>

    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/data_store_no_orm.py.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: base folder of generated files (relative to the project root) -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="dbal" sql="sdm/sql"/>

    <dto scope="" inheritance="" field-names-mode="0" macro=""/>

    <dao scope="" field-assign-mode="0" macro=""/>

    <ide event-log="true"/>

    <cpp class-prefix=""/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="mysql-connector-java-8.0.13.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/todolist" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.3.4.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/todolist" user="postgres" pwd="sa" />-->

    <type-map default="">

        <type detected="java.lang.Short" target="int"/>
        <type detected="java.lang.Integer" target="int"/>
        <type detected="java.lang.Long" target="long"/>

        <type detected="java.lang.Double" target="float"/>
        <type detected="java.lang.Float" target="float"/>
        <type detected="java.math.BigDecimal" target="float"/>

        <type detected="java.util.Date" target="str"/>
        <type detected="java.lang.String" target="str"/>
        <type detected="java.lang.Boolean" target="bool"/>
        <type detected="byte[]" target="bytes"/>

        <type detected="java.lang.Object" target="object"/>

    </type-map>

    <macros>
    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/data_store_sqlx.go.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="settings.xsd">

    <!-- target: the same as "module" in "go.mod" -->

    <!-- sql: base folder of SQL files (relative to the project root) -->

    <folders target="sdm_demo_todolist" sql="sqlx/sdm/sql"/>

    <!-- scope: base folder of generated DTO files (relative to the project root). -->

    <!-- field-names-mode: 0 - TitleCase -->

    <!-- macro: VM template to render DAO classes.

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dao ... macro="<path>/<name>.vm"/>

         Single VM template for both DTO and DAO is OK (like in VM examples from the tab "Admin").
         Separate VM templates for DTO and DAO are OK too. -->

    <dto scope="sqlx/dbal/dto" inheritance="" field-names-mode="0" macro=""/>

    <!-- scope: base folder of generated DAO files (relative to the project root). -->

    <!-- field-assign-mode (Go only)":

            0 - by column name
            1 - by position
            2 - ptr to DTO (Gorm, sqlx)
            >>> 3 - direct ptr to resulting slice of DTO-s (Gorm only). -->

    <!-- macro: VM template to render DAO classes.

            1. Internal VM template is used if "macro" is empty (default).
            2. VM template is located in "<macros>...<macro><vm>|<vm-xml>..." section below.
            3. Ending ".vm" means using of VM file and specifies the path to this file relative to the project root:
                    <dao ... macro="<path>/<name>.vm"/>

         Single VM template for both DTO and DAO is OK (like in VM examples from the tab "Admin").
         Separate VM templates for DTO and DAO are OK too. -->

    <dao scope="sqlx/dbal" field-assign-mode="2" macro="sqlx/sdm/go.vm"/>

    <ide event-log="true"/>

    <jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
          url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

    <!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
    <!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

    <!--    <jdbc jar="mysql-connector-java-8.0.13.jar" class="com.mysql.cj.jdbc.Driver"-->
    <!--          url="jdbc:mysql://localhost/todolist" user="root" pwd="sa"/>-->

    <!--    <jdbc jar="postgresql-42.3.4.jar" class="org.postgresql.Driver"-->
    <!--          url="jdbc:postgresql://localhost:5432/todolist" user="postgres" pwd="sa" />-->

    <type-map default="">

        <!-- sqlite3 -->

        <type detected="sqlx-java.lang.Integer" target="int64${json-sqlx} -> SetInt64"/>
        <type detected="sqlx-java.lang.Float" target="float32${json-sqlx} -> SetFloat64"/>
        <type detected="sqlx-java.lang.Double" target="float64${json-sqlx} -> SetFloat64"/>
        <type detected="sqlx-java.lang.String" target="string${json-sqlx} -> SetString"/>
        <type detected="sqlx-java.util.Date" target="time:time.Time${json-sqlx} -> SetTime"/>
        <type detected="sqlx-byte[]" target="byte[]{$json-sqlx} -> SetBytes"/>
        <type detected="sqlx-java.lang.Object" target="interface{}${json-sqlx}"/>

        <type detected="java.lang.Integer" target="int64${json} -> SetInt64"/>
        <type detected="java.lang.Float" target="float32${json} -> SetFloat64"/>
        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>
        <type detected="java.lang.String" target="string${json} -> SetString"/>
        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>
        <type detected="byte[]" target="byte[]{$json} -> SetBytes"/>
        <type detected="java.lang.Object" target="interface{}${json}"/>

        <!-- oracle -->

        <!--        <type detected="sqlx-java.math.BigDecimal" target="github.com/godror/godror:godror.Number${json-sqlx} -> SetNumber"/>-->
        <!--        <type detected="sqlx-java.math.BigDecimal+auto" target="github.com/godror/godror:godror.Number${json-sqlx}|1:;autoIncrement -> SetNumber"/>-->

        <!--        <type detected="sqlx-java.lang.String" target="string${json-sqlx} -> SetString"/>-->
        <!--        <type detected="sqlx-java.util.Date" target="time:time.Time${json-sqlx} -> SetTime"/>-->
        <!--        <type detected="sqlx-byte[]" target="string${json-sqlx}"/>-->
        <!--        <type detected="sqlx-java.lang.Boolean" target="int64${json-sqlx} -> SetBool"/>-->

        <!--        <type detected="sqlx-java.lang.Object" target="interface{}${json}-sqlx"/>-->

        <!--        <type detected="java.math.BigDecimal" target="github.com/godror/godror:godror.Number${json} -> SetNumber"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->
        <!--        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>-->
        <!--        <type detected="byte[]" target="string${json}"/>-->
        <!--        <type detected="java.lang.Boolean" target="int64${json} -> SetBool"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

        <!-- mysql, postgres -->

        <!--        <type detected="sqlx-java.util.UUID" target="github.com/google/uuid:uuid.UUID${json-sqlx}|1:;type:uuid"/>-->
        <!--        <type detected="sqlx-java.util.UUID+auto"-->
        <!--              target="github.com/google/uuid:uuid.UUID${json-sqlx}|1:;type:uuid;default:uuid_generate_v4()"/>-->

        <!--        <type detected="sqlx-java.lang.Short" target="int16${json-sqlx} -> SetInt16"/>-->
        <!--        <type detected="sqlx-java.lang.Integer" target="int32${json-sqlx} -> SetInt32"/>-->
        <!--        <type detected="sqlx-java.lang.Long" target="int64${json-sqlx} -> SetInt64"/>-->

        <!--        <type detected="sqlx-java.lang.Float" target="float32${json-sqlx} -> SetFloat32"/>-->
        <!--        <type detected="sqlx-java.lang.Double" target="float64${json-sqlx} -> SetFloat64"/>-->
        <!--        <type detected="sqlx-java.math.BigDecimal" target="float64${json-sqlx} -> SetFloat64"/>-->

        <!--        <type detected="sqlx-java.lang.String" target="string${json-sqlx} -> SetString"/>-->
        <!--        <type detected="sqlx-java.util.Date" target="time:time.Time${json-sqlx} -> SetTime"/>-->
        <!--        <type detected="sqlx-byte[]" target="string${json-sqlx}"/>-->
        <!--        <type detected="sqlx-java.lang.Boolean" target="bool${json-sqlx} -> SetBool"/>-->

        <!--        <type detected="sqlx-java.lang.Object" target="interface{}${json-sqlx}"/>-->

        <!--        <type detected="java.util.UUID" target="github.com/google/uuid:uuid.UUID${json} -> SetUUID"/>-->
        <!--        <type detected="java.sql.Array" target="[]string${json}"/>-->

        <!--        <type detected="java.lang.Short" target="int16${json} -> SetInt16"/>-->
        <!--        <type detected="java.lang.Integer" target="int32${json} -> SetInt32"/>-->
        <!--        <type detected="java.lang.Long" target="int64${json} -> SetInt64"/>-->

        <!--        <type detected="java.lang.Float" target="float32${json} -> SetFloat32"/>-->
        <!--        <type detected="java.lang.Double" target="float64${json} -> SetFloat64"/>-->
        <!--        <type detected="java.math.BigDecimal" target="float64${json} -> SetFloat64"/>-->

        <!--        <type detected="java.lang.String" target="string${json} -> SetString"/>-->
        <!--        <type detected="java.util.Date" target="time:time.Time${json} -> SetTime"/>-->
        <!--        <type detected="byte[]" target="string${json} -> "/>-->
        <!--        <type detected="java.lang.Boolean" target="bool${json} -> SetBool"/>-->

        <!--        <type detected="java.lang.Object" target="interface{}${json}"/>-->

    </type-map>

    <macros>

        <macro value="=built-in=" name="${column}"/>
        <macro value="=built-in=" name="${lower_snake_case(column)}"/>
        <macro value="=built-in=" name="${camelCase(column)}"/>
        <macro value="=built-in=" name="${TitleCase(column)}"/>
        <macro value="=built-in=" name="${kebab-case(column)}"/>

        <macro name="${col}" value="${lower_snake_case(column)}"/>

        <macro name="${json}" value=" `json:&quot;${col}${0}&quot;`"/>

        <macro name="${json-sqlx}"
               value=" `json:&quot;${col}${0}&quot; db:&quot;${column}&quot;`"/>

    </macros>

</settings>

=== panedrone/sqldalmaker/src/resources/DataStore_PDO_SQLite3.php.settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:noNamespaceSchemaLocation="settings.xsd">

	<!-- target: base folder of generated files (relative to the project root). -->

	<!-- sql: base folder of SQL files (relative to the project root) -->

	<folders target="api" sql="sdm/sql"/>

	<!-- scope: the name of DTO namespace. An empty one is OK. -->

	<!-- field-names-mode: 0 - TitleCase, 1 - camelCase; 2 - snake_case -->

	<dto scope="svc/dto" inheritance="" field-names-mode="2" macro=""/>

	<!-- scope: the name of DTO namespace. An empty one is OK. -->

	<dao scope="svc/dao" field-assign-mode="0" macro=""/>

	<ide event-log="true"/>

	<cpp class-prefix=""/>

	<jdbc jar="lib/sqlite-jdbc-3.42.0.0.jar" class="org.sqlite.JDBC"
		  url="jdbc:sqlite:$PROJECT_DIR$/todolist.sqlite" user="" pwd=""/>

	<!--    <jdbc jar="mysql-connector-java-8.0.13.jar" class="com.mysql.cj.jdbc.Driver"-->
	<!--          url="jdbc:mysql://localhost/todolist" user="root" pwd="sa"/>-->

	<!--    <jdbc jar="postgresql-42.3.4.jar" class="org.postgresql.Driver"-->
	<!--          url="jdbc:postgresql://localhost:5432/todolist" user="postgres" pwd="sa" />-->

	<!--    <jdbc jar="ojdbc10.jar" class="oracle.jdbc.driver.OracleDriver"-->
	<!--          url="jdbc:oracle:thin:@localhost:1521/XE" user="todolist" pwd="sa"/>-->

	<!--    <jdbc jar="mssql-jdbc-8.2.2.jre8.jar" class="com.microsoft.sqlserver.jdbc.SQLServerDriver"-->
	<!--          url="jdbc:sqlserver://localhost:1433;instance=SQLEXPRESS;databaseName=AdventureWorks2014" user="sa" pwd="root"/>-->

	<type-map default="">

		<type detected="java.lang.Short" target="int"/>
		<type detected="java.lang.Integer" target="int"/>
		<type detected="java.lang.Long" target="int"/>

		<type detected="java.lang.Float" target="float"/>
		<type detected="java.lang.Double" target="float"/>
		<type detected="java.math.BigDecimal" target="float"/>

		<type detected="java.util.Date" target="string"/>
		<type detected="java.lang.String" target="string"/>
		<type detected="java.lang.Boolean" target="bool"/>
		<type detected="byte[]" target="array"/>
		<type detected="java.lang.Object" target="object"/>

	</type-map>

	<macros>
	</macros>

</settings>
